name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: nemesiscodex/actix-todo-cache
    services:
      postgres:
        image: postgres:10.12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Move cache
      run: mv /cache/target .
    - name: Run migrations
      run: diesel migration run 
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    - name: Setup tests
      run: |
        echo "SERVER.HOST: 0.0.0.0" > .env
        echo "SERVER.PORT: 8080" >> .env
        echo "PG.USER: postgres" >> .env
        echo "PG.PASSWORD: postgres" >> .env
        echo "PG.HOST: postgres" >> .env
        echo "PG.PORT: 5432" >> .env
        echo "PG.DBNAME: postgres" >> .env
        echo "PG.POOL.MAX_SIZE: 30" >> .env
    - name: Run tests
      run: cargo test --verbose